# Generated by Django 5.2.7 on 2025-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_department_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reply_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
