# Generated by Django 5.2.7 on 2025-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_reply_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Menunggu Balasan'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='WAITING', max_length=20),
        ),
    ]
